lab03 & add gradle
UCSB-CS56-Projects/cs56-utilities-credit-card-validator pull request #33
Opened 2017-10-20 04:46 UTC by derenlei

Complete the F17_lab03.md and add the gradle which connects to the build.xml (issue #23 ). However the gradle might need to be rewritten to support future code adding.

2017-11-01 22:33 UTC, jaeaster requested changes

2017-11-01 22:33 UTC, EasterAndJay commented on build.gradle
> +mainClassName = "edu.ucsb.cs56.projects.utilities.credit_card_validator"
This line should be:
`mainClassName = "edu.ucsb.cs56.projects.utilities.credit_card_validator.Menu"`

2017-11-01 22:33 UTC, EasterAndJay commented on build.gradle
> +
On the following line add this:

`sourceSets.main.java.srcDirs` = ['src']

This says "Hey gradle, go look for my main class specified above in the `src` directory"

By default, gradle looks for a directory named `src/main/java/` for the start of your class path.

2017-11-01 22:35 UTC, EasterAndJay commented
Can you make a separate pull request for the gradle changes? This PR should only include the commit for the lab 03 assessment.

```

2017-11-02 02:13 UTC, closed without merging

2017-11-02 02:22 UTC, derenlei commented
I used the code above and this pull request is automatically closed. How can I do separate pull requests?

2017-11-02 05:17 UTC, EasterAndJay commented
@derenlei Don't worry about the pull requests for now we'll figure it out next week